CleanArch/Catalogo.WebUI/Controllers/CategoriasController.cs
using Catalogo.WebUI.Models;
using Catalogo.WebUI.Services;
using Microsoft.AspNetCore.Mvc;

namespace Catalogo.WebUI.Controllers;

public class CategoriasController : Controller
{
    private readonly ICategoriaServie _categoriaServie;

    public CategoriasController(ICategoriaServie categoriaServie)
    {
        _categoriaServie = categoriaServie ??
            throw new ArgumentNullException(nameof(categoriaServie));
    }

    [HttpGet]
    public async Task<IActionResult> Index()
    {
        var result = await _categoriaServie.GetCategorias();
        if (result is null)
            return View("Error");

        return View(result);
    }

    [HttpGet]
    public IActionResult CriarNovaCategoria()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> CriarNovaCategoria(CategoriaViewModel model)
    {
        if (ModelState.IsValid)
        {
            var result = await _categoriaServie.CriaCategoria(model);
            if (result != null)
                return RedirectToAction(nameof(Index));
        }

        ViewBag.Erro = "Erro ao criar Categoria";
        return View();
    }

    [HttpGet]
    public async Task<IActionResult> AtualizarCategoria(int id)
    {
        var result = await _categoriaServie.GetCategoriaPorId(id);
        if (result is null)
            return View("Error");

        return View(result);
    }

    [HttpPost]
    public async Task<IActionResult> AtualizarCategoria(int id, CategoriaViewModel model)
    {
        if (ModelState.IsValid)
        {
            var result = await _categoriaServie.AtualizaCategoria(id, model);
            if (result)
                return RedirectToAction(nameof(Index));
        }

        ViewBag.Erro = "Erro ao atualizar Categoria";
        return View(model);
    }

    [HttpGet]
    public async Task<IActionResult> DeletarCategoria(int id)
    {
        var result = await _categoriaServie.GetCategoriaPorId(id);
        if (result is null)
            return View("Error");

        return View(result);
    }

    [HttpPost, ActionName("DeletarCategoria")]
    public async Task<IActionResult> DeletaConfirmado(int id)
    {
        var result = await _categoriaServie.DeletaCategoria(id);
        if (result)
            return RedirectToAction(nameof(Index));

        return View("Error");
    }



}

CleanArch/Catalogo.WebUI/Controllers/ProdutosController.cs
using Catalogo.WebUI.Models;
using Catalogo.WebUI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Catalogo.WebUI.Controllers;

public class ProdutosController : Controller
{
    private readonly IProdutoService _produtoService;
    private readonly ICategoriaServie _categoriaServie;
    private string token = string.Empty;

    public ProdutosController(IProdutoService produtoService,
                              ICategoriaServie categoriaServie)
    {
        _produtoService = produtoService;
        _categoriaServie = categoriaServie;
    }

    [HttpGet]
    public async Task<IActionResult> Index()
    {
        var produtos = await _produtoService.GetProdutos(ObtemTokenJwt());
        if (produtos is null)
            return View("Error");

        return View(produtos);
    }


    [HttpGet]
    public async Task<IActionResult> CriarNovoProduto()
    {
        ViewBag.CategoriaId = new SelectList(
            await _categoriaServie.GetCategorias(), "Id", "Nome");

        return View();
    }

    [HttpPost]
    public async Task<IActionResult> CriarNovoProduto(ProdutoViewModel requestProduto)
    {
        if (ModelState.IsValid)
        {
            var produto = await _produtoService.CriaProduto(requestProduto, ObtemTokenJwt());
            if (produto != null)
                return RedirectToAction(nameof(Index));
        }

        ViewBag.CategoriaId = new SelectList(
            await _categoriaServie.GetCategorias(), "Id", "Nome");

        return View(requestProduto);
    }

    [HttpGet]
    public async Task<IActionResult> AtualizarProduto(int id)
    {
        var produto = await _produtoService.GetProdutoPorId(id, ObtemTokenJwt());
        if (produto is null)
            return View("Error");

        ViewBag.CategoriaId = new SelectList(
            await _categoriaServie.GetCategorias(), "Id", "Nome");

        return View(produto);
    }

    [HttpPost]
    public async Task<IActionResult> AtualizarProduto(int id, ProdutoViewModel requestProduto)
    {
        if (ModelState.IsValid)
        {
            var result = await _produtoService.AtualizaProduto(id, requestProduto, ObtemTokenJwt());
            if (result)
                return RedirectToAction(nameof(Index));
        }

        ViewBag.CategoriaId = new SelectList(
            await _categoriaServie.GetCategorias(), "Id", "Nome");

        return View(requestProduto);
    }

    [HttpGet]
    public async Task<IActionResult> DeletarProduto(int id)
    {
        var produto = await _produtoService.GetProdutoPorId(id, ObtemTokenJwt());
        if (produto is null)
            return View("Error");

        return View(produto);
    }

    [HttpPost, ActionName("DeletarProduto")]
    public async Task<IActionResult> DeletaConfirmado(int id)
    {
        if (ModelState.IsValid)
        {
            var result = await _produtoService.DeletaProduto(id, ObtemTokenJwt());
            if (result)
                return RedirectToAction(nameof(Index));
        }

        return View("Error");
    }


    private string ObtemTokenJwt()
    {
        if (HttpContext.Request.Cookies.ContainsKey("X-Access-Token"))
            token = HttpContext.Request.Cookies["X-Access-Token"].ToString();

        return token;
    }
}

CleanArch/Catalogo.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Catalogo.WebUI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Catalogo.WebUI.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" integrity="sha512-q3eWabyZPc1XTCmF+8/LuE1ozpg5xxn7iO89yfSOd5/oKvyqLngoNGsx8jq92Y8eXJ/IRxQbEC+FGSYxtk2oiw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Catalogo.WebUI</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Categorias" asp-action="Index">Categorias</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Produtos" asp-action="Index">Produtos</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav ms-lg-auto">
                        @await Html.PartialAsync("_LoginPartial")
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Catalogo.WebUI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>